app/__init__.py
from flask import Flask


def create_app():
    app= Flask(__name__)
    app.config.from_mapping(
        DEBUG = True,
        SECRETE_KEY = 'dev',
        SQLALCHEMY_DATABASE_URI = "sqlite:///inventario.db"
    )


    from app.main import main_bp


    app.register_blueprint(main_bp)


    return app  

app/main/__init__.py
from flask import Blueprint


main_bp = Blueprint('main', __name__, url_prefix='/')


from . import routes

app/main/routes.py
from flask import Flask, render_template, request, redirect, url_for
from app.main import main_bp
import pickle
import numpy as np

# IMPORTACIÓN DE MODELOS
################################################################################
with open('app/trained_models/rf_model.pkl', 'rb') as model: # Random Forest
    rf_clf = pickle.load(model) 

with open('app/trained_models/lr_model.pkl', 'rb') as model: # Random Forest
    lr_clf = pickle.load(model) 

with open('app/trained_models/knn_model.pkl', 'rb') as model: # Random Forest
    knn_clf = pickle.load(model) 

with open('app/trained_models/svm_model.pkl', 'rb') as model: # Random Forest
    svm_clf = pickle.load(model) 

#################################################################################


def validate_number(value):
    try:
        return float(value)
    except ValueError:
        return None

def validate_input(lensep, widsep, lenpet, widpet):
    lensep = validate_number(lensep)
    widsep = validate_number(widsep)
    lenpet = validate_number(lenpet)
    widpet = validate_number(widpet)

    return lensep, widsep, lenpet, widpet

@main_bp.route("/", methods=["GET", "POST"])
def get_variables():
    if request.method == 'POST':
        lensep = request.form.get("lensep")
        widsep = request.form.get("widsep")
        lenpet = request.form.get("lenpet")
        widpet = request.form.get("widpet")

        lensep, widsep, lenpet, widpet = validate_input(lensep, widsep, lenpet, widpet)

        # Comprobamos si alguna de las entradas no es válida (None)
        if None in [lensep, widsep, lenpet, widpet]:
            return "Por favor, ingrese valores numéricos válidos."

        return redirect(url_for('main.predicciones', lensep=lensep, widsep=widsep, lenpet=lenpet, widpet=widpet))
    
    return render_template("home.html")


@main_bp.route("/predicciones")
def predicciones(): 
    lensep = request.args.get('lensep')
    widsep = request.args.get('widsep')
    lenpet = request.args.get('lenpet')
    widpet = request.args.get('widpet')

    lensep, widsep, lenpet, widpet = validate_input(lensep, widsep, lenpet, widpet)

    # Comprobamos si alguna de las entradas no es válida (None)
    if None in [lensep, widsep, lenpet, widpet]:
        return "Por favor, ingrese valores numéricos válidos."

    # Arreglo de los valores introducidos
    inputs_to_pred = np.array([lensep, widsep, lenpet, widpet]).reshape(1, -1)

    # Predicción
    rf_pred = rf_clf.predict(inputs_to_pred)
    lr_pred = lr_clf.predict(inputs_to_pred)
    svm_pred = svm_clf.predict(inputs_to_pred)
    knn_pred = knn_clf.predict(inputs_to_pred)

    return render_template("home.html", rf_pred=rf_pred, lr_pred=lr_pred, svm_pred=rf_pred, knn_pred=knn_pred)

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iris ML-Predecir</title>
</head>
<body>
    <h1 class="h1 text-center mt-5 fw-light">Predicción de Especies de Iris</h1>
    <p class="text-center mt-3 font-monospace">Introduzca las variables y conozca a qué clase de Iris pertenece.</p>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-header text-center fw-light">Introduzca las variables</div>

                    <form action="{{ url_for('main.get_variables') }}"" method="post">
                        <div class="card-body p-5">
                            <div class="input-group ">
                                <div class="input-group-text w-50 fw-light">Longitud del Sépalo</div>
                                <input type="number" name="lensep" step="any" class="form-control col-1">
                            </div>
            
                            <div class="input-group mt-3">
                                <div class="input-group-text w-50 fw-light">Ancho del Sépalo</div>
                                <input type="number" name="widsep" step="any" class="form-control col-1">
                            </div>
            
                            <div class="input-group mt-3">
                                <div class="input-group-text w-50 fw-light">Longitud del Pétalo</div>
                                <input type="number" name="lenpet" step="any" class="form-control" value="Introduce un valor">
                            </div>
            
                            <div class="input-group mt-3">
                                <div class="input-group-text w-50 fw-light">Ancho del Pétalo</div>
                                <input type="number" name="widpet" step="any" class="form-control" value="Introduce un valor ">
                            </div>                       
                        </div> 
                        <button type="submit" class="btn btn-success mb-3 ms-5 fw-light">Predecir</button>
                    </form>

                </div>
            </div>
        </div>

    </div> <!-- container -->

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <!-- Sección de predicción -->
                <div class="card mt-5">
                    <div class="card-header text-center fw-light">Predicción</div>          
                    <div class="card-body">
                        
                        <div class="input-group mb-1">
                            <div class="input-group-text w-50 fw-light">Random Forest:</div>
                            <p class="form-control ms-3 mt-3 fw-light">{{ rf_pred }}</p>
                        </div>

                        <div class="input-group mb-1">
                            <div class="input-group-text w-50 fw-light">Logistic Regression:</div>
                            <p class="form-control ms-3 mt-3 fw-light">{{ lr_pred }}</p>
                        </div>

                        <div class="input-group mb-1">
                            <div class="input-group-text w-50 fw-light">Support Vector Machines:</div>
                            <p class="form-control ms-3 mt-3 fw-light">{{ svm_pred }}</p>
                        </div>

                        <div class="input-group mb-1">
                            <div class="input-group-text w-50 fw-light">K Nearest Neighbors:</div>
                            <p class="form-control ms-3 mt-3 fw-light">{{ knn_pred }}</p>
                        </div>
            
                    </div>   
                </div>
            </div> 
        </div>
    </div>
    
</body>

</html>